#!/usr/bin/env python3
"""
Stroke lettering for the AI's map drawings (D-118), from BAR's own typeface.

Reads the outlines of the characters the AI writes from a BAR font (Exo 2 Bold,
the game's UI typeface), flattens each curve into straight strokes, simplifies
them (Ramer-Douglas-Peucker), and writes an AngelScript table the AI draws as map
lines: outline lettering that the engine renders in its chalky, hand-drawn line
style. Only the characters of TEXTS are kept, so the table stays small.

    python tools/draw/make_glyphs.py [--font <ttf>] [--preview out.png]

Output: data/script/src/systems/presentation/glyphs.as (namespace Glyphs). Units are font
units scaled so the cap height is 1000; y grows downward (map z), baseline 0.
"""
import argparse
import math
import os
import sys

from fontTools.ttLib import TTFont
from fontTools.pens.basePen import BasePen

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_FONT = r"C:\bardev\bar-Beyond-All-Reason\fonts\exo2\Exo2-Bold.ttf"
OUT = os.path.join(REPO, "data", "script", "src", "manager", "glyphs.as")

# every text the AI writes (systems/presentation/commands.as): the table holds these characters
TEXTS = [
    "SMRTBARb",
    "Do not spec cheat!",
    "Contributors",
    "Lamer",
    "Centrifugal",
    "Felnious",
    "BarscrewlSports",
    "RobotRobert03",
    "ManBearPig",
    "iOS_Client",
    # D-127: the lane labels (systems/world/lanes.as): class names and numbers
    "LAND BOT AMPHIBIOUS HOVER ALL-TERRAIN NAVAL AIR LANES",
    "0123456789",
]
CURVE_STEPS = 5          # segments per quadratic / cubic curve before simplifying
SIMPLIFY = 32.0          # RDP tolerance in output units (cap height 1000)


class FlatPen(BasePen):
    """Collects closed contours as lists of points, curves flattened."""

    def __init__(self, glyphset):
        super().__init__(glyphset)
        self.contours = []
        self.cur = []

    def _moveTo(self, p):
        self.cur = [p]

    def _lineTo(self, p):
        self.cur.append(p)

    def _curveToOne(self, p1, p2, p3):
        p0 = self.cur[-1]
        for i in range(1, CURVE_STEPS + 1):
            t = i / CURVE_STEPS
            mt = 1 - t
            x = mt ** 3 * p0[0] + 3 * mt * mt * t * p1[0] + 3 * mt * t * t * p2[0] + t ** 3 * p3[0]
            y = mt ** 3 * p0[1] + 3 * mt * mt * t * p1[1] + 3 * mt * t * t * p2[1] + t ** 3 * p3[1]
            self.cur.append((x, y))

    def _qCurveToOne(self, p1, p2):
        p0 = self.cur[-1]
        for i in range(1, CURVE_STEPS + 1):
            t = i / CURVE_STEPS
            mt = 1 - t
            x = mt * mt * p0[0] + 2 * mt * t * p1[0] + t * t * p2[0]
            y = mt * mt * p0[1] + 2 * mt * t * p1[1] + t * t * p2[1]
            self.cur.append((x, y))

    def _closePath(self):
        if len(self.cur) > 2:
            if self.cur[0] != self.cur[-1]:
                self.cur.append(self.cur[0])
            self.contours.append(self.cur)
        self.cur = []

    _endPath = _closePath


def rdp(pts, eps):
    if len(pts) < 3:
        return pts
    a, b = pts[0], pts[-1]
    dx, dy = b[0] - a[0], b[1] - a[1]
    n = math.hypot(dx, dy)
    best, idx = -1.0, 0
    for i in range(1, len(pts) - 1):
        p = pts[i]
        d = abs(dy * p[0] - dx * p[1] + b[0] * a[1] - b[1] * a[0]) / n if n > 0 else math.hypot(p[0] - a[0], p[1] - a[1])
        if d > best:
            best, idx = d, i
    if best <= eps:
        return [a, b]
    return rdp(pts[: idx + 1], eps)[:-1] + rdp(pts[idx:], eps)


def simplify_closed(c, eps):
    # split the ring at its farthest point from the start so RDP keeps the shape
    far = max(range(len(c)), key=lambda i: math.hypot(c[i][0] - c[0][0], c[i][1] - c[0][1]))
    s = rdp(c[: far + 1], eps)[:-1] + rdp(c[far:], eps)
    return s if len(s) >= 4 else c


def build(font_path):
    font = TTFont(font_path)
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    os2 = font["OS/2"]
    cap = getattr(os2, "sCapHeight", 0) or font["head"].unitsPerEm * 0.7
    k = 1000.0 / cap
    hmtx = font["hmtx"]
    chars = sorted(set("".join(TEXTS)))
    glyphs = {}
    for ch in chars:
        name = cmap.get(ord(ch))
        if name is None:
            sys.exit("no glyph for %r in %s" % (ch, font_path))
        adv = hmtx[name][0] * k
        pen = FlatPen(gs)
        gs[name].draw(pen)
        contours = []
        for c in pen.contours:
            pts = [(x * k, -y * k) for x, y in c]      # y down: map z
            pts = simplify_closed(pts, SIMPLIFY)
            contours.append([(round(x), round(y)) for x, y in pts])
        glyphs[ch] = (round(adv), contours)
    return glyphs


def write_as(glyphs, font_path):
    lines = [
        "// Generated by tools/draw/make_glyphs.py from %s (D-118): do not edit." % os.path.basename(font_path),
        "// Stroke lettering for the AI's map drawings: per character its advance and",
        "// its outline as closed polylines. Cap height 1000, y down (map z), baseline 0.",
        "namespace Glyphs {",
        "    // CHARS[i] is described by DATA from START[i]: advance, then contours as",
        "    // point count followed by x, y pairs; -1 ends the character",
    ]
    order = sorted(glyphs)
    data, start = [], []
    total = 0
    for ch in order:
        adv, contours = glyphs[ch]
        start.append(len(data))
        data.append(adv)
        for c in contours:
            data.append(len(c))
            for x, y in c:
                data.extend([x, y])
            total += len(c) - 1
        data.append(-1)
    esc = "".join(order).replace("\\", "\\\\").replace('"', '\\"')
    lines.append('    const string CHARS = "%s";' % esc)
    lines.append("    const array<int> START = { %s };" % ", ".join(str(s) for s in start))
    rows = []
    for i in range(0, len(data), 24):
        rows.append("        " + ", ".join(str(v) for v in data[i:i + 24]))
    lines.append("    const array<int> DATA = {\n" + ",\n".join(rows) + "\n    };")
    lines.append("    // strokes in all characters: %d" % total)
    lines.append("}  // namespace Glyphs")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return total


def text_strokes(glyphs, text):
    n = 0
    for ch in text:
        if ch in glyphs:
            n += sum(len(c) - 1 for c in glyphs[ch][1])
    return n


def preview(glyphs, path):
    from PIL import Image, ImageDraw
    W, H = 1600, 900
    img = Image.new("RGB", (W, H), (60, 40, 35))
    d = ImageDraw.Draw(img)
    y = 120
    for text in TEXTS:
        size = 70 if text != "Contributors" else 90
        s = size / 1000.0
        x = 60
        for ch in text:
            adv, contours = glyphs[ch]
            for c in contours:
                pts = [(x + px * s, y + py * s) for px, py in c]
                d.line(pts, fill=(240, 240, 240), width=2)
            x += adv * s
        y += size * 1.9
    img.save(path)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--preview")
    a = ap.parse_args()
    glyphs = build(a.font)
    total = write_as(glyphs, a.font)
    print("wrote %s: %d characters, %d strokes" % (OUT, len(glyphs), total))
    for t in TEXTS:
        print("  %-22s %4d strokes" % (t, text_strokes(glyphs, t)))
    if a.preview:
        preview(glyphs, a.preview)
        print("preview: %s" % a.preview)


if __name__ == "__main__":
    main()
