"""Join BARb's configuration to the shared game knowledge base.

Reads the game cache produced by ../rjm.bar.docs/tools/knowledge/extract.py
(override with BAR_DOCS_DIR) plus this repository's data/config/*/ and
data/script/src/**/*.as, and writes doc/knowledge/barb-unit-config.md: one row
per reachable unit with BARb roles/attributes/limits/threat per config, factory
lists, AngelScript references, and the configuration gap lists.

Run:  python tools/knowledge/barb_report.py
"""
import collections
import glob
import io
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
DOCS = os.environ.get("BAR_DOCS_DIR", os.path.abspath(os.path.join(ROOT, "..", "rjm.bar.docs")))
CACHE = os.path.join(DOCS, "tools", "knowledge", ".cache", "kb.json")
OUT = os.path.join(ROOT, "doc", "knowledge", "barb-unit-config.md")
UNIT_LINK = "../../../rjm.bar.docs/knowledge/30-units/%s/%s.md"
FACTION_DIR = {"arm": "armada", "cor": "cortex", "leg": "legion"}


def read_json_relaxed(path):
    s = io.open(path, encoding="utf-8").read()
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    s = re.sub(r"(?m)//.*$", "", s)
    s = re.sub(r",(\s*[}\]])", r"\1", s)
    return json.loads(s)


def load_configs():
    cfgs = collections.OrderedDict()
    for cdir in sorted(glob.glob(os.path.join(ROOT, "data", "config", "*"))):
        if not os.path.isdir(cdir):
            continue
        beh, fac = {}, {}
        for f in glob.glob(os.path.join(cdir, "behaviour*.json")):
            beh.update(read_json_relaxed(f).get("behaviour", {}))
        for f in glob.glob(os.path.join(cdir, "factory*.json")):
            fac.update(read_json_relaxed(f).get("factory", {}))
        cfgs[os.path.basename(cdir)] = {"behaviour": beh, "factory": {k: v.get("unit", []) for k, v in fac.items() if isinstance(v, dict)}}
    return cfgs


def script_refs(unit_ids):
    refs = {u: {} for u in unit_ids}
    for f in glob.glob(os.path.join(ROOT, "data", "script", "src", "**", "*.as"), recursive=True):
        rel = os.path.relpath(f, ROOT).replace("\\", "/")
        s = io.open(f, encoding="utf-8", errors="replace").read()
        for uid in re.findall(r'"([a-z][a-z0-9_]{2,})"', s):
            if uid in refs:
                refs[uid][rel] = refs[uid].get(rel, 0) + 1
    return {u: r for u, r in refs.items() if r}


def faction_of(u):
    f = u["file"]
    if "/Legion/" in f or u["id"].startswith(("leg", "lee")):
        return "leg"
    if "/Arm" in f or u["id"].startswith("arm"):
        return "arm"
    return "cor"


def main():
    kb = json.load(open(CACHE, encoding="utf-8"))
    U = kb["units"]
    names = kb["names"]["names"]
    cfgs = load_configs()
    refs = script_refs(list(U))
    extra = set(kb["extra_units"])
    reach = {u for u, v in U.items() if v.get("reachable")}
    mobile = {u for u in reach if (U[u].get("speed") or 0) > 0}
    allbeh = set().union(*[set(c["behaviour"]) for c in cfgs.values()])
    allfac = set().union(*[set(x) for c in cfgs.values() for x in c["factory"].values()])

    def link(uid):
        return "[%s](%s)" % (names.get(uid, uid), UNIT_LINK % (FACTION_DIR.get(faction_of(U[uid]), "other"), uid))

    out = ["---", "layer: 90", "confidence: data (this repository's configs joined to the shared game cache)",
           "sources:", "  - data/config/*/behaviour*.json, factory*.json", "  - data/script/src/**/*.as",
           "  - ../rjm.bar.docs/tools/knowledge/.cache/kb.json (BAR %s)" % kb["meta"]["bar_commit"], "---", "",
           "# BARb unit configuration",
           "",
           "Generated by `tools/knowledge/barb_report.py`. Game facts about each unit are in the shared knowledge base "
           "(`../../../rjm.bar.docs/knowledge/30-units/`); this file holds only what BARb does with them. "
           "Configs: %s." % ", ".join("`%s`" % c for c in cfgs), ""]

    # ---- gap lists
    nocfg = sorted(u for u in mobile if u not in allbeh)
    nofac = sorted(u for u in mobile if u not in allfac and "COMMANDER" not in U[u]["categories"] and not U[u].get("workertime"))
    out += ["## Configuration gaps (commander-reachable mobile units)", "",
            "### In no behaviour config of any profile (%d)" % len(nocfg), ""]
    grp = collections.defaultdict(list)
    for u in nocfg:
        grp[(U[u]["domain"], "extra pack" if u in extra else "standard")].append(u)
    out += ["| Domain | Set | Units |", "| --- | --- | --- |"]
    for (d, s), lst in sorted(grp.items()):
        out.append("| %s | %s | %s |" % (d, s, ", ".join(link(u) for u in lst)))
    out += ["", "### Buildable but in no factory list of any profile - never produced (%d)" % len(nofac), ""]
    grp = collections.defaultdict(list)
    for u in nofac:
        grp[(U[u]["domain"], "extra pack" if u in extra else "standard")].append(u)
    out += ["| Domain | Set | Units |", "| --- | --- | --- |"]
    for (d, s), lst in sorted(grp.items()):
        out.append("| %s | %s | %s |" % (d, s, ", ".join(link(u) for u in lst)))
    out += ["", "### Missing per profile", "", "| Profile | Reachable mobile units without a behaviour entry |", "| --- | ---: |"]
    for c, cc in cfgs.items():
        out.append("| `%s` | %d |" % (c, sum(1 for u in mobile if u not in cc["behaviour"])))

    # ---- per-unit table
    out += ["", "## Per-unit configuration", "",
            "One row per commander-reachable unit. Roles/attributes are shown for `experimental_hard`; the *Differs* column lists profiles whose main role or attributes differ from it. Threat is the `threat` block where present.", "",
            "| Unit | Id | Domain | Main role | Roles | Attributes | Limit | Threat | Factory lists | Differs | Script refs |",
            "| --- | --- | --- | --- | --- | --- | ---: | --- | --- | --- | --- |"]
    prim = cfgs.get("experimental_hard") or next(iter(cfgs.values()))
    for uid in sorted(reach, key=lambda x: (faction_of(U[x]), (U[x]["customparams"].get("techlevel") or 1), x)):
        u = U[uid]
        e = prim["behaviour"].get(uid)
        roles = e.get("role", []) if e else []
        attrs = e.get("attribute", []) if e else []
        facs = sorted({f for c in cfgs.values() for f, lst in c["factory"].items() if uid in lst})
        differs = []
        for c, cc in cfgs.items():
            ee = cc["behaviour"].get(uid)
            if (ee is None) != (e is None) or (ee and e and (ee.get("role", [])[:1] != roles[:1] or ee.get("attribute", []) != attrs)):
                differs.append(c)
        thr = json.dumps(e["threat"], separators=(",", ":")) if e and e.get("threat") is not None else "-"
        rf = ", ".join("`%s` (%d)" % (os.path.basename(k), v) for k, v in sorted(refs.get(uid, {}).items()))
        out.append("| %s | `%s` | %s | %s | %s | %s | %s | %s | %s | %s | %s |" % (
            link(uid), uid, u["domain"], "`%s`" % roles[0] if roles else ("*absent*" if e is None else "-"),
            ", ".join("`%s`" % r for r in roles) or "-", ", ".join("`%s`" % a for a in attrs) or "-",
            e.get("limit", "-") if e else "-", "`%s`" % thr if thr != "-" else "-",
            ", ".join("`%s`" % f for f in facs) or "-", ", ".join("`%s`" % c for c in differs) or "-", rf or "-"))
    out += ["", "## Notes", "",
            "- *absent* means no behaviour entry: CircuitAI falls back to native defaults for role and attributes.",
            "- `rare` units are produced only through the rare-unit path, never as a standard factory pick.",
            "- Reachability is computed in the shared cache (BFS over `buildoptions` from the three commanders plus Extra Units Pack hosts).", ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("wrote", OUT, "| reachable", len(reach), "| no behaviour", len(nocfg), "| never produced", len(nofac))


if __name__ == "__main__":
    main()
